// Cameroon cities with their neighborhoods/areas
export const CAMEROON_CITIES_WITH_AREAS: Record<string, string[]> = {
  "Yaoundé": [
    "Bastos",
    "Étoudi",
    "Soa",
    "Nkondengui",
    "Melen",
    "Omnisports",
    "Akwa",
    "Awar escalier",
    "Awae village",
    "Mokolo",
    "Nlongkak",
    "Emombo",
    "Biyem-Assi",
    "Elig-Essono",
    "Nkoabang",
    "Efoulan",
    "Yaoundé 1",
    "Yaoundé 2",
    "Yaoundé 3",
    "Yaoundé 4",
    "Yaoundé 5",
    "Yaoundé 6",
    "Yaoundé 7",
    "Other"
  ],
  "Douala": [
    "Akwa",
    "Bonanjo",
    "Deido",
    "Bonabéri",
    "Nkongsa",
    "Kotto",
    "Logbaba",
    "Jalingo",
    "PK12",
    "Makepe",
    "Bassa",
    "Heili-Centre",
    "Douala 1",
    "Douala 2",
    "Douala 3",
    "Douala 4",
    "Douala 5",
    "Douala 6",
    "New Bell",
    "Mvog-Ada",
    "Other"
  ],
  "Bafoussam": [
    "Centre-Ville",
    "Nkongni",
    "Njunda",
    "Nsimalen",
    "Baleng",
    "Fongo-Tongo",
    "Chefferie",
    "Souffou",
    "Foumbot Road",
    "Menchum",
    "Mlong",
    "Nkafu",
    "Fongwente",
    "Njengekem",
    "Kamkop",
    "Banso",
    "Bayangam",
    "Fontem",
    "Baleng-West",
    "Nkongni-East",
    "Other"
  ],
  "Garoua": [
    "Centre-Ville",
    "Nkouandou",
    "Garoua 1",
    "Garoua 2",
    "Garoua 3",
    "Garoua 4",
    "Domayo",
    "Makabay",
    "Langada",
    "Baguere",
    "Benue",
    "Boulamari",
    "Gounare",
    "Ngaoundere Road",
    "Maroua Road",
    "Police Quartier",
    "Motaze",
    "Kabga",
    "Gari",
    "Kangsi",
    "Other"
  ],
  "Kumba": [
    "Centre-Ville",
    "Kumba 1",
    "Kumba 2",
    "Kumba 3",
    "Buea Road",
    "Mamfe Road",
    "Muea",
    "Ndibundisom",
    "Bwitingi",
    "Toke",
    "Keka",
    "Mbengwi",
    "Mbu",
    "Ngusi",
    "Owondo",
    "Fontem Road",
    "Mambanda",
    "Upper Station",
    "Lower Station",
    "Kumbo",
    "Other"
  ],
  "Bamenda": [
    "Centre-Ville",
    "New Town",
    "Bamenda 1",
    "Bamenda 2",
    "Bamenda 3",
    "Commercial Avenue",
    "Mankon Road",
    "Nkwen",
    "Nsongwa",
    "Achang",
    "Mendakwe",
    "Bamendakwe",
    "Sisia",
    "Tata",
    "Nsongwa-Upper",
    "Ngam",
    "Mfondonglan",
    "Nfagri",
    "Djindjem",
    "Bamaji",
    "Other"
  ],
  "Buea": [
    "Centre-Ville",
    "Buea 1",
    "Buea 2",
    "Buea 3",
    "Molyko",
    "Bokwango",
    "Great Soppo",
    "Small Soppo",
    "Bwititi",
    "Muyuka",
    "Tole",
    "Ekona",
    "Muea",
    "Bwassa",
    "Bafaw",
    "Meme",
    "Tiko Road",
    "Kumba Road",
    "Clegg",
    "Government Road",
    "Other"
  ],
  "Edéa": [
    "Centre-Ville",
    "Edéa 1",
    "Edéa 2",
    "Edéa 3",
    "Logindji",
    "Loc",
    "Songminkoa",
    "Okola",
    "Makénéné",
    "Logbessou",
    "Solowozo",
    "Dibamba",
    "Mbandje",
    "Bonakuma",
    "Songandi",
    "Bakoko",
    "Bakondji",
    "Loum Road",
    "Duala Road",
    "Yaoundé Road",
    "Other"
  ],
  "Limbe": [
    "Centre-Ville",
    "Limbe 1",
    "Limbe 2",
    "Limbe 3",
    "Down Beach",
    "Up Beach",
    "Botanical Garden",
    "Yaounde Road",
    "Buea Road",
    "Tiko Road",
    "Douala Road",
    "Mboka",
    "Bimbia",
    "Muea",
    "Mabeta",
    "Ndian",
    "Mutengene",
    "Bonakuma",
    "Bakweri",
    "Government Road",
    "Other"
  ],
  "Nkongsamba": [
    "Centre-Ville",
    "Nkongsamba 1",
    "Nkongsamba 2",
    "Nkongsamba 3",
    "Makombé",
    "Lokoti",
    "Douala Road",
    "Yaounde Road",
    "Edéa Road",
    "Loum",
    "Nkongzem",
    "Mabakot",
    "Makossa",
    "Mangamba",
    "Penda",
    "Bangangté Road",
    "Manyu",
    "Fontem Road",
    "Logbaba",
    "Nkondengui",
    "Other"
  ],
  "Mbalmayo": [
    "Centre-Ville",
    "Mbalmayo 1",
    "Mbalmayo 2",
    "Mbalmayo 3",
    "Okola",
    "Nlong",
    "Batié",
    "Makak",
    "Yaoundé Road",
    "Loum Road",
    "Nkongmondo",
    "Nomayos",
    "Nkaebam",
    "Kela",
    "Nsimalen",
    "Dibamba",
    "Bakouma",
    "Ebolowa Road",
    "Solowozo",
    "Njinteh",
    "Other"
  ],
  "Ebolowa": [
    "Centre-Ville",
    "Ebolowa 1",
    "Ebolowa 2",
    "Ebolowa 3",
    "Mvangan",
    "Mvolyé",
    "Kribi Road",
    "Yaounde Road",
    "Ambam Road",
    "Sangmelima Road",
    "Ngoumou",
    "Ngoulémakong",
    "Boloken",
    "Akak",
    "Ngoumou-Est",
    "Ngoumou-Ouest",
    "Oyama",
    "Zoetélé",
    "Minlaba",
    "Efoulan",
    "Other"
  ],
  "Bertoua": [
    "Centre-Ville",
    "Bertoua 1",
    "Bertoua 2",
    "Bertoua 3",
    "Battom",
    "Nguelekoug",
    "Batouri Road",
    "Yaounde Road",
    "Garoua Road",
    "Ngaoundéré Road",
    "Dimako",
    "Lomié",
    "Belabo",
    "Batouri",
    "Berbérati",
    "Ngoumougne",
    "Mbandje",
    "Ndokimadjé",
    "Kela",
    "Konga",
    "Other"
  ],
  "Ngaoundéré": [
    "Centre-Ville",
    "Ngaoundéré 1",
    "Ngaoundéré 2",
    "Ngaoundéré 3",
    "Mérigot",
    "Kodeni",
    "Arap",
    "Golda",
    "Garoua Road",
    "Yaounde Road",
    "Banyo",
    "Meiganga",
    "Tibati",
    "Ngandal",
    "Nyos",
    "Guider",
    "Gara",
    "Kougoultoum",
    "Nji",
    "Martap",
    "Other"
  ]
};

export function getCitiesList(): string[] {
  return Object.keys(CAMEROON_CITIES_WITH_AREAS).sort();
}

export function getAreasByCity(city: string): string[] {
  return CAMEROON_CITIES_WITH_AREAS[city] || [];
}
